import React from 'react';
import Head from 'next/head';
import { CartProvider } from '@/context/CartContext';
import MainHeader from '@/components/main-header';
import Footer from '@/components/footer';
import InlineCart from '@/components/inline-cart';
import { TransitionGroup, Transition } from 'react-transition-group';

const timeout = 100;

const styles = {
  entering: {
    position: 'absolute',
    opacity: 0,
  },
  entered: {
    transition: `opacity ${timeout}ms ease-in-out`,
    opacity: 1,
  },
  exiting: {
    transition: `opacity ${timeout}ms ease-in-out`,
    opacity: 0
  },
};

const Layout = (props) => {
  const handle = props.children.props.handle;
  const pageSpecificClass = `page--${handle}`;

  return (
    <CartProvider>
      <Head>
        <title>Doggonia Sandbox Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <InlineCart />
      <MainHeader />
      <main className="container">
        <TransitionGroup>
          <Transition key={handle} timeout={timeout}>
            {(status) => (
              <div className={pageSpecificClass} style={styles[status]}>
                {props.children}
              </div>
            )}
          </Transition>
        </TransitionGroup>
      </main>
      <Footer />
    </CartProvider>
  );
};

export default Layout;