import Head from 'next/head';

import HomepageHero from '../components/homepage-hero';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Doggonia Sandbox Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomepageHero />
      <h1>Doggonia</h1>
    </div>
  )
}
