import Head from 'next/head';

import HomepageHero from '@/components/homepage-hero';
import MissionStatment from '@/components/mission-statement';
import ValueProps from '@/components/value-props';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Doggonia Sandbox Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous" />
      </Head>
      <HomepageHero />
      <MissionStatment />
      <ValueProps />
    </div>
  )
}
